FROM golang:latest

RUN mkdir /app
WORKDIR /app
ENV GO111MODULE=on

RUN apt-get update && \
	apt-get -y install vim && \
	go get github.com/gin-gonic/gin && \
	go get github.com/go-sql-driver/mysql && \
	go get github.com/joho/godotenv && \
	go get github.com/jinzhu/gorm && \
	go get github.com/gin-contrib/cors